server:
  port: 8888
spring:
  application:
    name: configserver2
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZhangFWCode/springcloud.git
          searchPaths: config
          username: 2515526134@qq.com
          password: 19960917zfw
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/